# nginx deployment yaml with loadbalancer service 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
---
# YAML data
# Path: nginx-service.yaml
# nginx service yaml with loadbalancer service 
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
---
# # YAML data
# # Path: nginx-ingress.yaml
# # nginx ingress yaml with loadbalancer service 
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: nginx-ingress
#   labels:
#     app: nginx
# spec:
#   rules:
#   - host: nginx.example.com
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: nginx-service
#           servicePort: 80
---
# # YAML data
# # Path: nginx-deployment-with-secret.yaml
# # nginx deployment yaml with loadbalancer service and secret 
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment-with-secret
#   labels:
#     app: nginx
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.15.4
#         ports:
#         - containerPort: 80
#         volumeMounts:
#         - name: